---
id: gurk-01
base_name: programmer
tags:
- rabbit
- programmer
- guruby
presentation_date: 2013/03/09
version: 2013.3.9.0
licenses:
- CC BY-SA 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
